# Generated by Django 2.2.6 on 2019-11-16 17:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20191007_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='ashdkjhaskjdh', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='autor',
            name='imagen',
            field=models.URLField(default='ashdkjhaskjdh', max_length=250, verbose_name='URL de la imagen'),
        ),
    ]
