# Generated by Django 2.2.6 on 2019-11-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20191116_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='instagram',
        ),
        migrations.AddField(
            model_name='autor',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
    ]
