# Generated by Django 2.2.6 on 2019-11-16 23:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20191116_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='No hay información', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.URLField(default='https://cdn.icon-icons.com/icons2/1879/PNG/512/iconfinder-7-avatar-2754582_120519.png', max_length=250, verbose_name='URL de la imagen'),
        ),
    ]
